### ISSUE TITLE
Fails when comparing Invalid Dates

### ISSUE THREAD

**Issue by wysher** [lukeed/dequal#18]
I tried to use dequal as lodash.isEqual replacement, but find out that when comparing two Invalid Dates dequal returns true.

Not sure if this is correct, because of possible false possitives - new Date('foo') is not same as new Date('bar'). Solution - instead of comparing date.getTime(), isNaN(date) should be considered.

Again, not sure what result to expect here plus changing this will cause BREAKING-CHANGE.

I'll stick with lodash's isEqual for now :(

**Comment by lukeed** [comment]
Thanks, but I believe it should be treated as equal. Lodash isn't correct in all cases (Map and Set especially).

For example, this is the same as:

```js
dequal(
  { a: sum(2,3) },
  { b: sum(1, 4) },
)
```

The input parameters are different, but they're both evaluated as `5`. 

In the case of Dates, they're both still date instances & altho they're `Invalid Date`s, they still have the same resulting _value_.

Finally, two `NaN` values are considered equal. I know this is true with most libraries, including lodash I think, so that would be very weird to suddenly treat `NaN` differently because it's wearing a Date mask.

Closing, but I hope that makes sense.
Thanks!
