### ISSUE TITLE
Doesn't compare Sets

### ISSUE THREAD

**Issue by franleplant** [lukeed/dequal#2]
Hi!

I just noticed this library does not compare Sets correctly.

Repro:

```javascript

var dequal = require("dequal")

let a = new Set([1,2,3,4])
let b = new Set([1,2,3,4])

console.log(dequal(a,b))
```

https://runkit.com/embed/yiu9lr2kont0

As an example, lodash's `isEqual` does compare Sets and in the above use case does
return true.

This is also related to https://github.com/kentcdodds/use-deep-compare-effect/issues/15

Fran

**Comment by lukeed** [comment]
Thanks 👍 

I'll add this in a new "full" mode that pairs with the `klona` modes. (https://github.com/lukeed/klona/issues/13)

I took a quick stab at it tonight & it's pretty straightforward – but I'm traveling right now (aka distracted) so I won't get this in until I have full coverage. 

There are also some other "housekeeping" things I want to do here as part of the next release... since it's been a year since this module came out :)

Sneak peek:

```
Benchmark:
  assert.deepStrictEqual x 206,599 ops/sec ±1.43% (95 runs sampled)
  util.isDeepStrictEqual x 206,122 ops/sec ±1.11% (90 runs sampled)
  fast-deep-equal        x 438,723 ops/sec ±0.68% (96 runs sampled)
  lodash.isEqual         x 187,258 ops/sec ±0.99% (95 runs sampled)
  nano-equal             x 405,115 ops/sec ±1.27% (96 runs sampled)
  dequal                 x 459,977 ops/sec ±0.75% (97 runs sampled)
  dequal-alt             x 482,869 ops/sec ±0.41% (96 runs sampled)
```

**Comment by franleplant** [comment]
thanks a lot!

**Comment by Mika83AC** [comment]
Is this issue fixed, or still pending to be merged into a upcoming release?

With current version 1.0.1 it still doesn't work as expected: [https://runkit.com/embed/1v44o5w8nqze](https://runkit.com/embed/1v44o5w8nqze)

**Comment by lukeed** [comment]
It's not released yet. I'll push to have both dequal & klona 2.0 done this week – they go hand in hand.

**Comment by Mika83AC** [comment]
Great, thank you @lukeed !
