### ISSUE TITLE
Minor suggestion -- add "strict" option for "loose" equality

### ISSUE THREAD

**Issue by CarlosNZ** [lukeed/dequal#23]
Great library, thanks ! 👍

One small suggestion -- it's be nice if we could select between "loose" or "strict" equality checking. Currently, `dequal(1, true)` returns `false`, which is correct if we're checking `1 === true`, but not for `1 == true`. Similar for `dequal(null, undefined)`. 

Any chance of making the type of equality check configurable?

**Comment by lukeed** [comment]
Hey, thanks!

No, that defeats the purpose of the library. It's checking for deep strict equality, not loose equality. If there's enough interest over time, we can add a `dequal/loose` mode that will do this, but I doubt it'll be asked for since these kinds of comparisons are typically the cause for many bugs in JS land.

**Comment by CarlosNZ** [comment]
Fair enough, thanks for the reply.

I guess it's easy enough to do a little pre-processing before passing to `dequal` if we really want this. I'm working on  a library where loose equality is sometimes preferable, but I can handle this separately.

**Comment by CarlosNZ** [comment]
Fair enough, thanks for the reply.

I guess it's easy enough to do a little pre-processing before passing to `dequal` if we really want this. I'm working on  a library where loose equality is sometimes preferable (particularly `null == undefined`), but I can handle this separately.
