### ISSUE TITLE
Doesn't compare object with prototype

### ISSUE THREAD

**Issue by dy** [lukeed/dequal#3]
```js
dequal(Object.create({x:1}), {x:1}) //false
```
Other deep equal libs do that fine.

**Comment by lukeed** [comment]
Thanks, will take a look! Have some other changes in progress for this lib too

**Comment by lukeed** [comment]
Hey,

I was on the move when I first looked at this issue. This **should** be false.

An object with `x` on the _prototype_ is strictly not the same thing as an object with an `x` (writable, enumerable) property. 

Not sure what other libraries you were looking at/comparing with, but if they're meant to be a "deep equality" check, then they have a bug.

Confirmed with two others below:

```js
const fequal = require("fast-deep-equal");
const dequal = require("dequal");
const lodash = require("lodash");

console.log(`fast: ${fequal(Object.create({x:1}), {x:1})}`); //=> false
console.log(`dequal: ${dequal(Object.create({x:1}), {x:1})}`); //=> false
console.log(`lodash: ${lodash.isEqual(Object.create({x:1}), {x:1})}`); //=> false
```

Hope that helps!

**Comment by dy** [comment]
The fact that `dequal(el.childNodes, [...el.childNodes])` returns false is just disappointing.

**Comment by lukeed** [comment]
@dy that is not what you opened an issue about.

Also, **Arrays** can be strictly deep-equal with that syntax, but not `NodeList`s because that's of different type (iterator). Iterators are not currently supported but will be in the new mode I'll ship soon, which already includes Map and Set support. I may generalize that to any Iterator type.

What you can do in the meantime, since it sounds like you're explicitly checking for `childNodes`, is cast the NodeList to an Array via `list = Array.from(el.childNodes);` – that will then work out of the box.

***Proof:***

```js
var dequal = require("dequal")
var fequal = require("fast-deep-equal")
var lodash = require("lodash");

var items = [1, 2, 3]

console.log('dequal:', dequal(items, [...items])); //=> true
console.log('fequal:', fequal(items, [...items])); //=> true
console.log('lodash:', lodash.isEqual(items, [...items])); //=> true
```

**Comment by dy** [comment]
> I'll ship soon

Looking forward.

> I may generalize that to any Iterator type

Strings may be confusing though
