### ISSUE TITLE
Array Comparison

### ISSUE THREAD

**Issue by anywhichway** [lukeed/dequal#7]
There may be cases when your Array comparison breaks. Although not necessarily a good coding approach, sometimes non-numeric values are added to Arrays by programmers for book-keeping (The "arrays" in the DOM, e.g. attributes, are kind of like this). If you simply delete the Array section of your code, the unit tests still pass since arrays are just regular objects that only have numeric keys by default plus a length property and some extra functions. Also your code will be slightly smaller while also addressing this edge case.

**Comment by lukeed** [comment]
Hey,

While I know this to be true, it's done intentionally for performance reasons. Iterating Arrays in an Array-like manner is optimized for iterating Arrays 😜 It's a drastic performance difference, which you can see here too: https://github.com/lukeed/clsx/commit/91f5e68be63770493f61e93781c2ce72daece7e7

In this case, it's also preferable since we can use the lengths as an early bailout.

Thank you though, appreciate the heads up

**Comment by anywhichway** [comment]
True ... wrote an long Medium article on the topic of optimizing arrays. Perhaps an options arg to the main function with a switch? Or, just keep simple and document?

**Comment by lukeed** [comment]
It's perfect as is IMO. The array-likes you're describing (eg, NodeList) are just that, Array-like, and don't match the Array constructor.

And it's not worth trading ~40b for 200-600% performance
